CREATE DATABASE DB_BOOKWIZ;
USE DB_BOOKWIZ;

-- INSERT INTO TB_USER_ADM (UADM_NOME, UADM_IDADE, UADM_SEXO, UADM_EMAIL) values ('Bruno Trova', 18, 'Masculino', 'brunotrova@gmail.com');
-- SELECT * FROM TB_USER_ADM;

-- CREATE TABLE TB_LIVRO (
-- 	LV_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     LV_TITULO VARCHAR(200) NOT NULL,
--     LV_AUTOR VARCHAR(200) NOT NULL,
--     LV_GENERO VARCHAR(200) NOT NULL,
--     LV_DATCAD DATETIME NOT NULL,
--     LV_AVALIA TINYINT NOT NULL,
--     LV_DESCR VARCHAR(1000) NOT NULL
-- );

-- CREATE TABLE TB_USER_COM (
-- 	UC_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     UC_NOME VARCHAR(200) NOT NULL,
--     UC_IDADE INT,
--     UC_SEXO VARCHAR(200),
--     UC_EMAIL VARCHAR(200) NOT NULL,
--     UC_GENFAV VARCHAR(200) NOT NULL,
--     UC_ATIVO TINYINT NOT NULL DEFAULT 1
-- );

-- CREATE TABLE TB_USER_ADM (
-- 	UADM_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
--     UADM_NOME VARCHAR(200) NOT NULL,
--     UADM_IDADE INT,
--     UADM_SEXO VARCHAR (200),
--     UADM_EMAIL VARCHAR(200) NOT NULL,
--     UADM_ATIVO TINYINT NOT NULL DEFAULT 1
-- );
