/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookwiz.bookwiz.screens;


import com.bookwiz.bookwiz.DAO.LivroDAO;
import com.bookwiz.bookwiz.DAO.NotaDAO;
import com.bookwiz.bookwiz.entity.Livro;
import com.bookwiz.bookwiz.entity.Nota;
import com.bookwiz.bookwiz.entity.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author rai
 */
public class AdicionarLivroFrame extends javax.swing.JFrame {
    Usuario usuario;

    /**
     * Creates new form AdicionarLivroFrame
     */
    public AdicionarLivroFrame() {
        initComponents();
    }
    
    public AdicionarLivroFrame(Usuario usuario){
        this();
        this.usuario = usuario;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTextField = new javax.swing.JTextField();
        autorTextField = new javax.swing.JTextField();
        generoTextField = new javax.swing.JTextField();
        descricaoTextField = new javax.swing.JTextField();
        notaTextField = new javax.swing.JTextField();
        AdicionarLivroLabel = new javax.swing.JLabel();
        voltarButtonVoltar = new javax.swing.JButton();
        addButtonAdd = new javax.swing.JButton();
        romanceLabel = new javax.swing.JLabel();
        ficcaoLabel = new javax.swing.JLabel();
        tecnicoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));

        autorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));

        generoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));

        descricaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        notaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota"));

        AdicionarLivroLabel.setText("Adicionar novo livro");

        voltarButtonVoltar.setText("Voltar");
        voltarButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonVoltarActionPerformed(evt);
            }
        });

        addButtonAdd.setText("Adicionar ");
        addButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAddActionPerformed(evt);
            }
        });

        romanceLabel.setText("1 - Romance");

        ficcaoLabel.setText("2 - Ficção");

        tecnicoLabel.setText("3 - Técnico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(AdicionarLivroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(voltarButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(addButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(223, 223, 223))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notaTextField)
                            .addComponent(descricaoTextField)
                            .addComponent(generoTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(romanceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ficcaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tecnicoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(57, 57, 57))
                            .addComponent(autorTextField))
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(AdicionarLivroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(tituloTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(romanceLabel)
                    .addComponent(ficcaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tecnicoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricaoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(102, 102, 102))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonVoltarActionPerformed
        MenuFrame screen = new MenuFrame(usuario);
        this.dispose();
        screen.setVisible(true);
    }//GEN-LAST:event_voltarButtonVoltarActionPerformed

    private void addButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAddActionPerformed
        try {
            String titulo = tituloTextField.getText();
            String autor = autorTextField.getText();
            int genero = Integer.parseInt(generoTextField.getText());
            String desc = descricaoTextField.getText();
            int nota = Integer.parseInt(notaTextField.getText());
            if(nota < 0 || nota > 10){
                nota = Integer.parseInt(JOptionPane.showInputDialog("nota inserida é invalido, digite novamente uma nota entre 0 a 10"));
            }

            var livroNovo = new Livro(titulo, autor, desc, genero);
            var livroDAO = new LivroDAO();
            livroDAO.adicionarLivro(livroNovo);
            
            var notaLivro = new Nota(nota);
            var notaDAO = new NotaDAO();
            notaDAO.adicionarNota(notaLivro, usuario, livroNovo);
            
            JOptionPane.showMessageDialog(null, "Livro novo adicionado com sucesso");
            this.dispose();
            MenuFrame screen = new MenuFrame(usuario);
            screen.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_addButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarLivroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarLivroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdicionarLivroLabel;
    private javax.swing.JButton addButtonAdd;
    private javax.swing.JTextField autorTextField;
    private javax.swing.JTextField descricaoTextField;
    private javax.swing.JLabel ficcaoLabel;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JTextField notaTextField;
    private javax.swing.JLabel romanceLabel;
    private javax.swing.JLabel tecnicoLabel;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JButton voltarButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
