/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookwiz.bookwiz.screens;

import com.bookwiz.bookwiz.Usuario;
import com.bookwiz.bookwiz.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author rai
 */
public class AdicionarUsuarioFrame extends javax.swing.JFrame {
    
    Usuario usuario;

    /**
     * Creates new form AdicionarUsuarioFrame
     */
    public AdicionarUsuarioFrame() {
        initComponents();
    }
    
    public AdicionarUsuarioFrame(Usuario usuario) {
        this();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        idadeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        sexoTextField = new javax.swing.JTextField();
        generoTextField = new javax.swing.JTextField();
        addButtonAdd = new javax.swing.JButton();
        voltarButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        senhaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));

        idadeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade"));

        emailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));

        sexoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        generoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero Preferido"));

        addButtonAdd.setText("Adicionar");
        addButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAddActionPerformed(evt);
            }
        });

        voltarButtonVoltar.setText("Voltar");
        voltarButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonVoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Adicionar usuario novo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(emailTextField)
                    .addComponent(sexoTextField)
                    .addComponent(generoTextField)
                    .addComponent(jLabel1)
                    .addComponent(addButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginTextField)
                    .addComponent(senhaTextField)
                    .addComponent(idadeTextField))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButtonVoltar)
                .addGap(522, 522, 522))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sexoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(voltarButtonVoltar)
                .addContainerGap())
        );

        loginTextField.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarButtonVoltarActionPerformed

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void addButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAddActionPerformed
        try {
            String login = loginTextField.getText();
            String senha = senhaTextField.getText();
            int idade = Integer.parseInt(idadeTextField.getText());
            String email = emailTextField.getText();
            String sexo = sexoTextField.getText();
            int pref = Integer.parseInt(generoTextField.getText());

            var usuarioNovo = new Usuario(login, senha, email, sexo, pref, idade);
            var usuarioDAO = new UsuarioDAO();
            usuarioDAO.adicionarUsuario(usuarioNovo);
            JOptionPane.showMessageDialog(null, "Usuario novo adicionado com sucesso");
            AdminFrame screen = new AdminFrame(usuario);
            this.dispose();
            screen.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
        }
    }//GEN-LAST:event_addButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarUsuarioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButtonAdd;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JTextField idadeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JTextField sexoTextField;
    private javax.swing.JButton voltarButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
