/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bookwiz.bookwiz.screens;

import com.bookwiz.bookwiz.entity.Usuario;
import com.bookwiz.bookwiz.DAO.UsuarioDAO;
import java.awt.event.ItemEvent;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rai
 */
public class AtivarUsuarioInativoFrame extends javax.swing.JFrame {
    Usuario usuario, usuarioSelecionado;
    String email;
    int id;
    Usuario[] usuarios;
    
    /**
     * Creates new form AtivarUsuarioInativoFrame
     */
    public AtivarUsuarioInativoFrame() {
        initComponents();
    }
    
    public AtivarUsuarioInativoFrame(Usuario usuario) {
        this();
        this.usuario = usuario;
        setLocationRelativeTo(null);
        buscarUsuarioInativos();
    }
    
    private void buscarUsuarioInativos() {
        try {
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarios = usuarioDAO.obterUsuariosInativos();
            Arrays.sort(usuarios);
            listarUsuariosInativosComboBox.setModel(
                    new DefaultComboBoxModel<>(usuarios)
            );
            usuarioSelecionado = usuarios[0];
                
            email = usuarioSelecionado.getEmail();
            id = usuarioSelecionado.getId();
                
            emailusuarioSelecionadoLabel.setText(email);
            idUsuarioSelecionadoLabel.setText(Integer.toString(id));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(
            null, 
            "não encontrei lista de usuarios inativos");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listarUsuariosInativosComboBox = new javax.swing.JComboBox<>();
        emailusuarioSelecionadoLabel = new javax.swing.JLabel();
        idUsuarioSelecionadoLabel = new javax.swing.JLabel();
        reativarUsuarioButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listarUsuariosInativosComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listarUsuariosInativosComboBoxItemStateChanged(evt);
            }
        });
        listarUsuariosInativosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUsuariosInativosComboBoxActionPerformed(evt);
            }
        });

        emailusuarioSelecionadoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));

        idUsuarioSelecionadoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        reativarUsuarioButton.setText("Reativar usuario");
        reativarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reativarUsuarioButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listarUsuariosInativosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(emailusuarioSelecionadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(idUsuarioSelecionadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reativarUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(listarUsuariosInativosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailusuarioSelecionadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(idUsuarioSelecionadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(reativarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarUsuariosInativosComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listarUsuariosInativosComboBoxItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            usuarioSelecionado = (Usuario)evt.getItem();
            email = usuarioSelecionado.getEmail();
            id = usuarioSelecionado.getId();
        }
        
        emailusuarioSelecionadoLabel.setText(email);
        idUsuarioSelecionadoLabel.setText(Integer.toString(id));
    }//GEN-LAST:event_listarUsuariosInativosComboBoxItemStateChanged

    private void reativarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reativarUsuarioButtonActionPerformed
        try {
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            usuarioDAO.ativarUsuario(usuarioSelecionado);
            JOptionPane.showMessageDialog(null, "Usuario " + usuarioSelecionado.getNome() +" com id " + usuarioSelecionado.getId() + " foi reativado com sucesso");
            buscarUsuarioInativos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro " + e.getMessage());
        }
    }//GEN-LAST:event_reativarUsuarioButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        AdminFrame screen = new AdminFrame(usuario);
        screen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void listarUsuariosInativosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUsuariosInativosComboBoxActionPerformed
    }//GEN-LAST:event_listarUsuariosInativosComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtivarUsuarioInativoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtivarUsuarioInativoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtivarUsuarioInativoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtivarUsuarioInativoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtivarUsuarioInativoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailusuarioSelecionadoLabel;
    private javax.swing.JLabel idUsuarioSelecionadoLabel;
    private javax.swing.JComboBox<Usuario> listarUsuariosInativosComboBox;
    private javax.swing.JButton reativarUsuarioButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
